development:
  contact_form_recipient: maggie@intridea.com
  host: localhost:3000
  opentok:
    key: 3277692
    secret: 8905050f8367fa22748f910906d6a1dfe3b035f8
    js_src: http://staging.tokbox.com/v0.91/js/TB.min.js
  facebook:
    app_id: 212476088833208 
    app_secret: f19bacc518befd7f113963024b04adf3

test:
  contact_form_recipient: maggie@intridea.com
  opentok:
    key: 3277692
    secret: 8905050f8367fa22748f910906d6a1dfe3b035f8
    js_src: http://staging.tokbox.com/v0.91/js/TB.min.js
  facebook:
    app_id: 212476088833208
    app_secret: f19bacc518befd7f113963024b04adf3

staging:
  contact_form_recipient: maggie@intridea.com
  host: studyhall.intridea.com
  opentok:
    key: 5822951
    secret: df6d6a2dd7dd308d72b4b041ac2a2f7866fb985d
    js_src: https://swww.tokbox.com/v0.91/js/TB.min.js
  facebook:
    app_id: 178338135584982
    app_secret: 32979dcdcb2f545df4488dc28899ba1e

production:
  contact_form_recipient: ross@studyhall.com
  host: studyhall.com
  opentok:
    key: 5822951
    secret: df6d6a2dd7dd308d72b4b041ac2a2f7866fb985d
    js_src: https://swww.tokbox.com/v0.91/js/TB.min.js
  facebook:
    app_id: 
    app_secret: 
