development:
  bucket: bucket-dev
  access_key_id: AKIAIETU7HT7R2K3PCYQ
  secret_access_key: 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
test:
  bucket: bucket-test
  access_key_id: AKIAIETU7HT7R2K3PCYQ
  secret_access_key: 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
production:
  bucket: bucket-prod
  access_key_id: AKIAIETU7HT7R2K3PCYQ
  secret_access_key: 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
